version: '3.8'

services:
  event_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=local
    depends_on:
      - postgresql_database
    networks:
      - event-platform-network

  postgresql_database:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_DB=EventStoreDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - event-platform-network

networks:
  event-platform-network:
    driver: bridge

volumes:
  postgres-data: