version: '3.8'

services:
  event_service:
    build:
      context: .
      dockerfile: EventService.Api/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=local
    depends_on:
      - mongodb_database
    networks:
      - event-platform-network

  mongodb_database:
    image: mongo:latest
    container_name: eventservice.db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd!
      - MONGO_INITDB_DATABASE=EventStoreDb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - event-platform-network

networks:
  event-platform-network:
    driver: bridge

volumes:
  mongodb-data: 