version: '3.8'

services:
  ticket_service:
    build:
      context: .
      dockerfile: TicketService.Api/Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=local
    depends_on:
      - postgresql_database
    networks:
      - ticket-network

  postgresql_database:
    image: postgres:15
    container_name: ticketservice.db
    environment:
      - POSTGRES_DB=TicketStoreDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket-network

volumes:
  postgres_data:

networks:
  ticket-network:
    driver: bridge